<?php

// All the PHP files current working directory is the same location as this
// file. When sourcing this file, you have to use the following path:
// ./config.php
// Thanks to our router, sourcing this file is only made once and all the files
// inherit from these value without sourcing this file at all.

// Global configuration items.
// To use global variable, we need to prefix them with the "global" keyword
// each time we want to get the value, this is annoying.
// We can also make a class with static values or use the GLOBALS PHP
// initialized/defined array.
// However, having the value residing in memory means the value can always be
// accessed. If unstrusted PHP code can be run, this can cause security
// concerns. Let's use define instead as they are being generated by
// preprocessor only.
// The drawback is that with the "define" keyword, we cannot use the dollar
// symbol in order to access the element, we need to use the name.
define("ROOT_CGI", "./");
define("ROOT_WEB", "./");
?>
